# Generated by Django 2.1.7 on 2019-07-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydroserver_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeseries',
            name='begin_date',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='end_date',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='method_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='method_link',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='sample_medium',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='site_name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='value_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='variable_name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
