# Generated by Django 2.1.7 on 2019-07-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydroserver_core', '0002_auto_20190709_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeseries',
            name='begin_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
