# Generated by Django 2.1.7 on 2019-07-11 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hydroserver_core', '0004_auto_20190709_2304'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Timeseries',
            new_name='Reference',
        ),
    ]
