# Generated by Django 2.1.5 on 2019-01-16 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('collection_id', models.TextField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('collection_id', models.TextField()),
                ('database_id', models.TextField(default='None')),
                ('database_name', models.TextField(default='None')),
                ('database_path', models.TextField(default='None')),
                ('database_type', models.TextField(default='None')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
